# cw2 config
name: cw_cql
import_path: "./cw_cql.yaml"
import_exp: "cw_cql"

repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: &iterations 35000
num_checkpoints: 1

# Hardware specific parameters
params:
#  sampler:
#    args:
#      num_env_train: 4
#      num_env_test: 4
#      episodes_per_train_env: 1
#      episodes_per_test_env: 1
  projection:
    args:
      total_train_steps: *iterations

